### ISSUE TITLE
Complete Android track

### ISSUE THREAD

**Issue by mullinswebworx** [mullinswebworx/Treehouse#2]
## TODO

_Courses left in Android track_
- [x] Build a simple Android app
- [ ] Build an interactive story app
- [ ] Build a weather app
- [ ] Android lists and adapters
- [ ] Android activity lifecycle
