### ISSUE TITLE
Complete Github Basics course

### ISSUE THREAD

**Issue by mullinswebworx** [mullinswebworx/Treehouse#4]
## TODO
- Sections left to complete 
- [x] Hello, GitHub!
- [x] Working By Yourself
- [x] Working on a Team
- [x] Create a Web Presence on GitHub
- [x] Get Involved in Open Source

@realalysonla @kdaigle Thanks for making this course. 

![learning](https://cloud.githubusercontent.com/assets/1458299/16010332/8fa2302c-3135-11e6-851a-4f2022adac71.jpg)

**Comment by alysonla** [comment]
Nice! ⚡️⚡️⚡️

**Comment by mullinswebworx** [comment]
Very informative Thanks again for the course @alysonla and @kdaigle! 🎆 🎆
